//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUC.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LUC.Globalization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to the list of ignored directories.
        /// </summary>
        public static string Label_AddToIgnoreFolders {
            get {
                return ResourceManager.GetString("Label_AddToIgnoreFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Label_Attention {
            get {
                return ResourceManager.GetString("Label_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        public static string Label_ChangeFolder {
            get {
                return ResourceManager.GetString("Label_ChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change sync folder.
        /// </summary>
        public static string Label_ChangeSyncFolder {
            get {
                return ResourceManager.GetString("Label_ChangeSyncFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current folder:.
        /// </summary>
        public static string Label_CurrentFolder {
            get {
                return ResourceManager.GetString("Label_CurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string Label_DeleteFolder {
            get {
                return ResourceManager.GetString("Label_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Label_Exit {
            get {
                return ResourceManager.GetString("Label_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit confirmation.
        /// </summary>
        public static string Label_ExitConfirmation {
            get {
                return ResourceManager.GetString("Label_ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Label_LogInto {
            get {
                return ResourceManager.GetString("Label_LogInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Label_LogOut {
            get {
                return ResourceManager.GetString("Label_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout confirmation.
        /// </summary>
        public static string Label_LogoutConfirmation {
            get {
                return ResourceManager.GetString("Label_LogoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Label_Ok {
            get {
                return ResourceManager.GetString("Label_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Label_PleaseWait {
            get {
                return ResourceManager.GetString("Label_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selective sync.
        /// </summary>
        public static string Label_SelectFolderForIgnore {
            get {
                return ResourceManager.GetString("Label_SelectFolderForIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token was expired or incorrect access token, please login again..
        /// </summary>
        public static string Label_TokenExpired {
            get {
                return ResourceManager.GetString("Label_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload my folder to the server.
        /// </summary>
        public static string Label_UploadServerDeletedFolder {
            get {
                return ResourceManager.GetString("Label_UploadServerDeletedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} doesn&apos;t exist on the server. If you click &quot;Yes&quot;, your folder will be uploaded to the server, if &quot;No&quot;, it will be deleted on the current computer, if &quot;Cancel&quot;, it will be added to the list of folders that are ignored when synchronizing with the server..
        /// </summary>
        public static string Message_CreatedFolderOffline {
            get {
                return ResourceManager.GetString("Message_CreatedFolderOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want exit now?.
        /// </summary>
        public static string Message_DoYouWantExitNow {
            get {
                return ResourceManager.GetString("Message_DoYouWantExitNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to logout now?.
        /// </summary>
        public static string Message_DoYouWantLogoutNow {
            get {
                return ResourceManager.GetString("Message_DoYouWantLogoutNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection at the moment....
        /// </summary>
        public static string Message_NoConnection {
            get {
                return ResourceManager.GetString("Message_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root folder does not exist. Please login again..
        /// </summary>
        public static string Message_RootFolderDoesNotExist {
            get {
                return ResourceManager.GetString("Message_RootFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password.
        /// </summary>
        public static string Message_WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("Message_WrongLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create directory {0}. Please check access to parent folder..
        /// </summary>
        public static string MessageTemplate_CantCreateBucket {
            get {
                return ResourceManager.GetString("MessageTemplate_CantCreateBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not login. Please contact our support team. Status code: {0}.
        /// </summary>
        public static string MessageTemplate_CantLogin {
            get {
                return ResourceManager.GetString("MessageTemplate_CantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is already locked by user {1}. Contacts: {2}.
        /// </summary>
        public static string MessageTemplate_LockedFile {
            get {
                return ResourceManager.GetString("MessageTemplate_LockedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was renamed to {1}. Probably it is locked on server by another user or folder with the same name already exists..
        /// </summary>
        public static string MessageTemplate_RenamedFile {
            get {
                return ResourceManager.GetString("MessageTemplate_RenamedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server time and local time is different. Please try sync your local time. Your UTC time is {0}, server UTC time is {1}. Please login again later..
        /// </summary>
        public static string MessageTemplate_ServerAndLocalTimeIsDifferent {
            get {
                return ResourceManager.GetString("MessageTemplate_ServerAndLocalTimeIsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select action.
        /// </summary>
        public static string Title_SelectAction {
            get {
                return ResourceManager.GetString("Title_SelectAction", resourceCulture);
            }
        }
    }
}
